2019-06-28 09:11:01,931 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:01,946 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:01,951 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:01,962 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:01,966 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:01,970 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:01,974 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:01,978 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:01,985 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:01,989 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:01,992 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:01,997 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,005 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,011 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,015 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,023 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,034 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,038 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,043 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,048 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,057 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,066 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,072 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,079 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,084 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,102 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,110 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,122 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,130 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,135 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,141 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,146 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,154 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,159 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,164 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,169 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,177 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,186 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,194 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,199 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,208 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,213 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,218 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,223 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,228 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,233 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,238 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,243 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,251 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,259 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,277 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,286 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,308 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,326 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,334 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,346 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,351 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,369 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,388 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,410 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,415 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,420 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,432 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,470 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,475 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,501 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,506 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,514 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,519 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,527 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,545 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,564 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,574 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,586 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,595 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,636 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,649 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,657 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,728 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,772 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:02,786 - root - ERROR - utils  - 153 - JD(2245024)报错信息：数据库保存/更新失败
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 161, in save_data
    c.execute(sql)
cx_Oracle.IntegrityError: ORA-00001: 违反唯一约束条件 (EIP.ECOMMERCE_REVIEW_PK)
2019-06-28 09:11:03,121 - root - ERROR - utils  - 153 - JD(11463583653)报错信息：None
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 73, in js2py
    comm_dict = json.loads(comment[0])  # 将json对象obj解码为对应的字典dict
IndexError: list index out of range
2019-06-28 09:11:03,121 - root - ERROR - utils  - 153 - JD(11463583653)报错信息：无总评分数据
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 100, in conments
    productCommentSummary = comm_dict['productCommentSummary']
KeyError: 'productCommentSummary'
2019-06-28 09:11:21,012 - root - ERROR - utils  - 153 - JD(7438547)报错信息：None
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 73, in js2py
    comm_dict = json.loads(comment[0])  # 将json对象obj解码为对应的字典dict
IndexError: list index out of range
2019-06-28 09:11:21,013 - root - ERROR - utils  - 153 - JD(7438547)报错信息：无总评分数据
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 100, in conments
    productCommentSummary = comm_dict['productCommentSummary']
KeyError: 'productCommentSummary'
2019-06-28 09:11:39,983 - root - ERROR - utils  - 153 - JD(24818305875)报错信息：None
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 73, in js2py
    comm_dict = json.loads(comment[0])  # 将json对象obj解码为对应的字典dict
IndexError: list index out of range
2019-06-28 09:11:39,984 - root - ERROR - utils  - 153 - JD(24818305875)报错信息：无总评分数据
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 100, in conments
    productCommentSummary = comm_dict['productCommentSummary']
KeyError: 'productCommentSummary'
2019-06-28 09:11:58,157 - root - ERROR - utils  - 153 - JD(100002501954)报错信息：None
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 73, in js2py
    comm_dict = json.loads(comment[0])  # 将json对象obj解码为对应的字典dict
IndexError: list index out of range
2019-06-28 09:11:58,157 - root - ERROR - utils  - 153 - JD(100002501954)报错信息：无总评分数据
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 100, in conments
    productCommentSummary = comm_dict['productCommentSummary']
KeyError: 'productCommentSummary'
2019-06-28 09:12:17,702 - root - ERROR - utils  - 153 - JD(27115314210)报错信息：None
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 73, in js2py
    comm_dict = json.loads(comment[0])  # 将json对象obj解码为对应的字典dict
IndexError: list index out of range
2019-06-28 09:12:17,702 - root - ERROR - utils  - 153 - JD(27115314210)报错信息：无总评分数据
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 100, in conments
    productCommentSummary = comm_dict['productCommentSummary']
KeyError: 'productCommentSummary'
2019-06-28 09:12:37,493 - root - ERROR - utils  - 153 - JD(8031600)报错信息：None
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 73, in js2py
    comm_dict = json.loads(comment[0])  # 将json对象obj解码为对应的字典dict
IndexError: list index out of range
2019-06-28 09:12:37,494 - root - ERROR - utils  - 153 - JD(8031600)报错信息：无总评分数据
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 100, in conments
    productCommentSummary = comm_dict['productCommentSummary']
KeyError: 'productCommentSummary'
2019-06-28 09:12:55,993 - root - ERROR - utils  - 153 - JD(100001470134)报错信息：None
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 73, in js2py
    comm_dict = json.loads(comment[0])  # 将json对象obj解码为对应的字典dict
IndexError: list index out of range
2019-06-28 09:12:55,993 - root - ERROR - utils  - 153 - JD(100001470134)报错信息：无总评分数据
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 100, in conments
    productCommentSummary = comm_dict['productCommentSummary']
KeyError: 'productCommentSummary'
2019-06-28 09:13:16,032 - root - ERROR - utils  - 153 - JD(34326476497)报错信息：None
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 73, in js2py
    comm_dict = json.loads(comment[0])  # 将json对象obj解码为对应的字典dict
IndexError: list index out of range
2019-06-28 09:13:16,033 - root - ERROR - utils  - 153 - JD(34326476497)报错信息：无总评分数据
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 100, in conments
    productCommentSummary = comm_dict['productCommentSummary']
KeyError: 'productCommentSummary'
2019-06-28 09:13:34,312 - root - ERROR - utils  - 153 - JD(100001667527)报错信息：None
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 73, in js2py
    comm_dict = json.loads(comment[0])  # 将json对象obj解码为对应的字典dict
IndexError: list index out of range
2019-06-28 09:13:34,313 - root - ERROR - utils  - 153 - JD(100001667527)报错信息：无总评分数据
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 100, in conments
    productCommentSummary = comm_dict['productCommentSummary']
KeyError: 'productCommentSummary'
2019-06-28 09:13:55,176 - root - ERROR - utils  - 153 - JD(7224868)报错信息：None
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 73, in js2py
    comm_dict = json.loads(comment[0])  # 将json对象obj解码为对应的字典dict
IndexError: list index out of range
2019-06-28 09:13:55,177 - root - ERROR - utils  - 153 - JD(7224868)报错信息：无总评分数据
Traceback (most recent call last):
  File "C:/Users/BruceChen/Desktop/Demo/reviews/JD/jd_review.py", line 100, in conments
    productCommentSummary = comm_dict['productCommentSummary']
KeyError: 'productCommentSummary'
